### PR TITLE
Added Footer Section

### PR DESCRIPTION
**Pull request by Gauravmitra-hash**
Linked Issue: #37

### CODE REVIEW

**Review by singhayushh — APPROVED** [review]
Changes approved. We will be merging the PR shortly.
Thank you for contributing to KGEC Summer of Code'21!

**Review by Codehackerone — APPROVED** [review]

**Comment by Codehackerone** [comment]
@singhayushh Shouldn't the footer page be separate?

**Comment by singhayushh** [comment]
> @singhayushh Shouldn't the footer page be separate?

Yeah, it is in partials/footer.ejs. Check

**Comment by Codehackerone** [comment]
Alright! Merge it then.

**Pull request merged**
