### PR TITLE
Issue 10

### PR DESCRIPTION
**Pull request by saggy2001**
#10 

## Changes

- updated checkPhone() function in register.js
- added a new route '/api/phone-number/:id' in the user.route.js
- added apiPhone function to user.controller.js
- added apiPhone function to user.service.js to check phone number is present in the database or not
- updated the id of input element with id='phone' to id='phone-number' in register.ejs

### CODE REVIEW

**Review by Codehackerone — COMMENTED** [review]
Everything looks okay to me, but is there any specific reason that you changed the id of the phone number field from `phone` to `phone-number`?

**Comment by saggy2001** [comment]
> Everything looks okay to me, but is there any specific reason that you changed the id of the phone number field from `phone` to `phone-number`?

**Comment by saggy2001** [comment]
issue-10
Yes, if I don't change that then in the call_ajax function key will be 'phone' and then the tooltip will show the message 'phone already registered' that sounds weird.

**Comment by Codehackerone** [comment]
Okay Cool!

**Review by Codehackerone — APPROVED** [review]
Good to Merge.

**Pull request merged**
